name: tcr-deep-insight
channels:
  - conda-forge
  - bioconda
  - pytorch
dependencies:
  - conda-forge::python=3.8
  - conda-forge::setuptools=59.5.0
  - conda-forge::pip
  - bioconda::mafft
  - pip:
      - --extra-index-url https://download.pytorch.org/whl/cu117
      - --extra-index-url https://pypi.nvidia.com
      - faiss-gpu==1.7.2
      - transformers==4.17.0
      - datasets==1.18.4
      - anndata==0.8.0
      - scanpy==1.8.1
      - scikit-learn==0.24.1 
      - matplotlib==3.3.4 
      - einops==0.4.1 
      - biopython==1.79
      - seaborn==0.12.2
      - torch==1.13.1+cu117
      - torchvision==0.14.1+cu117
      - torchaudio==0.13.1+cu117
      - cuml==23.04.01
      - dask_cuda==v23.04.00
      - dask==2023.3.2
